### ISSUE TITLE
Erro encontrado

### ISSUE THREAD

**Issue by evssousa** [Alanamatos000/projeto6-visitando-novas-cidades#1]
Nome dos arquivos escritos incorretamente.

**Comment by Alanamatos000** [comment]
Corrigi todos já, esqueci de avisar

**Comment by Alanamatos000** [comment]
> Corrigi todos já, esqueci de avisar

**Comment by evssousa** [comment]
Uso de `array`, `function `e `forEach`. Fazer projeto sem isso.

**Comment by Alanamatos000** [comment]
Corrigido.

**Comment by evssousa** [comment]
Continua com `array` e `function`.
Correção finalizada.

**Comment by Alanamatos000** [comment]
Corrigido.

**Comment by evssousa** [comment]
Finalizado
